variables:
  buildConfiguration: Release

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: 'restore'
    projects: |
      Simmetric.IO.Csv/Simmetric.IO.Csv.csproj
      Simmetric.IO.Csv.Test/Simmetric.IO.Csv.Test.csproj
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'
    projects: |
      Simmetric.IO.Csv/Simmetric.IO.Csv.csproj
      Simmetric.IO.Csv.Test/Simmetric.IO.Csv.Test.csproj
    arguments: '--no-restore -c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: 'Simmetric.IO.Csv.Test/Simmetric.IO.Csv.Test.csproj'
    arguments: '--no-build --nologo -c $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'

- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    command: 'pack'
    packagesToPack: 'Simmetric.IO.Csv/Simmetric.IO.Csv.csproj'
    configuration: '$(buildConfiguration)'
    nobuild: true
    includesymbols: true
    versioningScheme: 'off'

- task: PublishCodeCoverageResults@1
  displayName: publish coverage results
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/coverage.*.cobertura.xml'
    failIfCoverageEmpty: true